<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="elbow_module"
               params="name child length1 twist1 length2 twist2">
  <link name="${name}|INPUT_INTERFACE">
    <visual>
      <origin xyz="0 0 ${length1/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${length1}" radius=".0254" />
      </geometry>
      <xacro:silver_material/>
    </visual>
    <visual>
      <origin xyz="-0.0274 0.0782 ${length1-0.007}" rpy="1.57075 0 ${twist1}" />
      <geometry>
        <mesh filename="package://hebiros/meshes/elbow_corner.stl"/>
      </geometry>
      <xacro:silver_material/>
    </visual>
  </link>
  <xacro:collar parent="${name}|INPUT_INTERFACE"/>
  <joint name="${name}|MID_ELBOW_JOINT" type="fixed">
    <parent link="${name}|INPUT_INTERFACE"/>
    <child link="${name}|AFTER_CORNER_BODY"/>
    <origin xyz="0 0 ${length1+.0254}" rpy="${-PI/2} 0 ${twist1}"/>
  </joint>
  <link name="${name}|AFTER_CORNER_BODY">
    <visual>
      <origin xyz="0 0 ${(length2/2)+.0254}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${length2}" radius=".0254" />
      </geometry>
      <xacro:silver_material/>
    </visual>
  </link>
  <joint name="${name}|OUTPUT_INTERFACE" type="fixed">
    <parent link="${name}|AFTER_CORNER_BODY"/>
    <child link="${child}|INPUT_INTERFACE"/>
    <origin xyz="0 0 ${length2+.0254}" rpy="0 0 ${twist2}"/>
  </joint>

  </xacro:macro>
</robot>
