<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="extension_module" params="name child length twist">
    <link name="${name}|INPUT_INTERFACE">
      <visual>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${length}" radius=".0254" />
        </geometry>
        <xacro:silver_material/>
      </visual>
    </link>
    <joint name="${name}|OUTPUT_INTERFACE" type="fixed">
      <parent link="${name}|INPUT_INTERFACE"/>
      <child link="${child}|INPUT_INTERFACE"/>
      <origin xyz="0 0 ${length}" rpy="0 0 ${twist}"/>
    </joint>
    <xacro:collar parent="${name}|INPUT_INTERFACE"/>
  </xacro:macro>
</robot>
